import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.scss";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { ThemeProvider } from "@/providers/theme-provider";
import TopLoader from "@/components/TopLoader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TopLoader />
          <div className="flex items-start justify-between">
            <div className="fixed top-0 bottom-0 w-[250px] min-h-dvh shadow-lg z-10 hidden lg:block">
              <Sidebar />
            </div>
            <main className="w-full min-h-dvh lg:pl-[250px] pl-0">
              <Header />
              <div className="p-8">{children}</div>
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
